### ISSUE TITLE
Error when calling 'Add to playlist' with a Playlist path

### ISSUE THREAD

**Issue by GrantDG** [3ll3d00d/jriver_homeassistant#24]
I'm attempting to execute an 'Add to playlist' action with a playlist path. The following error is being logged:

`Error: JRiverMediaPlayer.async_add_media_to_playlist() missing 1 required positional argument: 'query'`

The automation YAML is:

```YAML
alias: Test JRiver Add To Playlist
description: ""
triggers: []
conditions: []
actions:
  - action: jriver.add_to_playlist
    metadata: {}
    data:
      playlist_path: Morning Music\Acid Jazz
    target:
      device_id: aefb9c9d12424ae7d504c8353e297e4d
mode: single

```
